<?php
/**
 * MyExtension_Mymodule extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       MyExtension
 * @package        MyExtension_Mymodule
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Articulo link widget template
 *
 * @category    MyExtension
 * @package     MyExtension_Mymodule
 * @author      Ultimate Module Creator
 */
?>
<?php $_articulo = $this->getCurrentArticulo();?>
<?php if ($_articulo) :?>
    <div class="articulo-widget-link">
        <a href="<?php echo $_articulo->getArticuloUrl()?>"><?php echo $_articulo->getTitulo()?></a>
    </div>
<?php endif;?>
