<?php
/**
 * MyExtension_Mymodule extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       MyExtension
 * @package        MyExtension_Mymodule
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Articulo subtree template
 *
 * @category    MyExtension
 * @package     MyExtension_Mymodule
 * @author      Ultimate Module Creator
 */
?>
<?php $_articulos = $this->getArticulos(); ?>
<?php if ($_articulos->getSize() > 0) :?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/myextension_mymodule/tree.js')?>"></script>
    <ul id="<?php echo $this->getUniqueId()?>">
        <?php foreach ($_articulos as $_articulo) : ?>
            <?php echo $this->drawArticulo($_articulo);?>
        <?php endforeach;?>
    </ul>
    <script type="text/javascript">
        mymoduleTree('<?php echo $this->getUniqueId()?>');
    </script>
<?php endif;?>
