<?php
/**
 * MyExtension_Mymodule extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       MyExtension
 * @package        MyExtension_Mymodule
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Articulo view template
 *
 * @category    MyExtension
 * @package     MyExtension_Mymodule
 * @author      Ultimate Module Creator
 */
?>
<?php $_articulo = $this->getCurrentArticulo();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title articulo-title">
    <h1><?php echo $_articulo->getTitulo(); ?></h1>
</div>
<div class="articulo-view">
    <div class="articulo-titulo">
        <?php echo Mage::helper('myextension_mymodule')->__('Titulo');?>:<?php echo $_articulo->getTitulo();?>

    </div>

</div>
